name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
    - name: Lint Code
      run: terraform fmt --check --diff
